name: CI/CD Pipeline

on:
  workflow_dispatch:  # manual trigger

jobs:
  Deploy_app:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/meetup-web:latest
            sudo docker run -d --name myapp -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/meetup-web:latest
